// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/SAMPO-BU/sampo-server/internal/app/config"
	"github.com/SAMPO-BU/sampo-server/internal/app/container"
	"github.com/SAMPO-BU/sampo-server/pkg/database"
	"github.com/labstack/echo/v4"
	"strconv"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	echoEcho := echo.New()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	dbConfig := config.NewDBConfig()
	databaseConfig, err := provideDBConfig(dbConfig)
	if err != nil {
		return nil, err
	}
	db, err := database.New(databaseConfig)
	if err != nil {
		return nil, err
	}
	app := container.NewApp(echoEcho, configConfig, db)
	return app, nil
}

// wire.go:

func provideDBConfig(cfg *config.DBConfig) (*database.Config, error) {
	port, err := strconv.Atoi(cfg.Port)
	if err != nil {
		return nil, err
	}

	return &database.Config{
		Host:     cfg.Host,
		Port:     uint(port),
		User:     cfg.User,
		Password: cfg.Password,
		DBName:   cfg.DBName,
	}, nil
}
