// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Kurichi/go-template/internal/app/config"
	"github.com/Kurichi/go-template/internal/app/container"
	"github.com/Kurichi/go-template/pkg/database"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func New() (*container.App, error) {
	echoEcho := echo.New()
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	dbConfig := config.NewDBConfig()
	databaseConfig := provideDBConfig(dbConfig)
	db, err := database.New(databaseConfig)
	if err != nil {
		return nil, err
	}
	app := container.NewApp(echoEcho, configConfig, db)
	return app, nil
}

// wire.go:

func provideDBConfig(cfg *config.DBConfig) *database.Config {
	return &database.Config{}
}
