# for deployment
FROM golang:1.20.1-alpine3.17
RUN apk update && apk add --no-cache git && apk add --no-chace curl
ENV GO_ENV /go/src/app/
ENV TZ Asia/Tokyo
WORKDIR ${GO_ENV}
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
ENTRYPOINT [ "go", "run", "main.go"]