
FROM golang:1.20.1-alpine3.17

RUN apk update && apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN export GO_ENV=/go/src/app/

RUN go install  github.com/ramya-rao-a/go-outline@latest
RUN go install golang.org/x/tools/gopls@latest

# Hot Reload
RUN go install github.com/cosmtrek/air@v1.29.0

CMD ["air", "-c", ".air.toml"]