// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func InitServer() *echo.Echo {
	echoEcho := InitEcho()
	return echoEcho
}
